apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiz

resources:
  - namespace.yml
  - secrets.yml

helmCharts:
- name: wiz-kubernetes-integration
  repo: https://charts.wiz.io/
  releaseName: wiz-kubernetes-integration
  namespace: wiz
  valuesFile: values.yml
  version: 0.1.95