# The ExternalSecret describes what data should be fetched, how the data should be transformed and saved as a Kind=Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiz-sa
  namespace: wiz
spec:
  refreshInterval: 60m  # Sync every 60 minutes
  secretStoreRef:      # References the ClusterSecretStore (lighthouse-secrets) that connects to AWS.
    name: lighthouse-secrets    #The ClusterSecretStore (lighthouse-secrets) used to authenticate with AWS and fetch the AWS secret manager secrets  
    kind: ClusterSecretStore
  target:
    name: wiz-sa  #  The Kubernetes Secret that will be created.
  data:           # Maps wiz service account secret fields to Kubernetes Secret keys.
    - secretKey: clientId    # Kubernetes Secret key
      remoteRef:
        key: wiz-client-id  # AWS Secrets Manager secret name
        property: clientId  # JSON key inside the secret in AWS Secrets Manager 
    - secretKey: clientToken
      remoteRef:
        key: wiz-client-secret # AWS Secrets Manager secret name
        property: clientToken  # JSON key inside the secret in AWS Secrets Manager 


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiz-sensor-imagepullkey
  namespace: wiz

spec:
  refreshInterval: 60m
  secretStoreRef:
    name: lighthouse-secrets
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
    name: sensor-image-pull
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: sensor-image-pull-cred-3