apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lh-dev1
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: "*"
        repoURL: https://github.com/ridlawiz/argocd-demo  # Update repoURL here
        revision: main
  template:
    metadata:
      name: "{{index .path.segments 0}}"
    spec:
      project: default
      destination:
        namespace: "{{index .path.segments 0}}"
        server: "https://kubernetes.default.svc"
      sources:
        - repoURL: https://github.com/ridlawiz/argocd-demo
          targetRevision: main
          path: "{{index .path.segments 0}}/helm/"
