apiVersion: v2
appVersion: "2.8"
dependencies:
- name: wiz-common
  repository: https://wiz-sec.github.io/charts
  version: 0.1.6
description: Wiz admission controller
name: wiz-admission-controller
type: application
version: 3.8.8
